services:
  script:
    build:
      context: .
    expose:
      - 5000
    labels:
      traefik.enable: true
      traefik.http.routers.eagle.rule: Host(`mail-eagle.sanabau.com`)
      traefik.http.routers.eagle.tls: true
      traefik.http.routers.eagle.tls.certresolver: pertls
      traefik.http.routers.eagle.entrypoints: https,http
      traefik.docker.network: traefik
    volumes:
      - ./config:/app/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      LOGIN: root
      PASSWORD: pas
    networks:
      - traefik

networks:
  traefik:
    external: false